image: mcr.microsoft.com/dotnet/core-nightly/sdk:3.0.100-alpine3.10

variables:
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: "3"

stages:
  - test

test:
    stage: test
    script:
    - ls -A
    - chmod +x ./build.sh
    - /bin/sh ./build.sh Test
